services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./certs:/var/www/html/certs
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://petrucodes.ro
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=laravelpass
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  cert_data:
